// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(platform_macosFFI)
import platform_macosFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_platform_macos_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_platform_macos_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol CaptureSessionProtocol : AnyObject {

    /**
     * Start capturing. All coordinates must be in CG screen space (top-left
     * origin, y increasing downward — same as CGEventGetLocation and the AX API).
     *
     * Call `poll_event()` on a timer (~16 ms) after this returns to consume events.
     */
    func activate(viewX: Double, viewY: Double, viewW: Double, viewH: Double, targetX: Double, targetY: Double, targetW: Double, targetH: Double, escapeTaps: UInt32, escapeIntervalMs: UInt64) throws

    /**
     * Convenience: activate with `Rect` structs and default escape settings
     * (3 Option-key taps within 1 second).
     */
    func activateWithRects(viewRect: Rect, targetRect: Rect) throws

    /**
     * Activate with a selected CGWindowID so forwarded mouse events carry
     * window-local hit-test coordinates and background-window routing fields.
     */
    func activateWithWindowId(viewRect: Rect, targetRect: Rect, targetWindowId: UInt32) throws

    /**
     * Stop capturing and restore the system cursor. Idempotent.
     */
    func deactivate()

    /**
     * Drain all pending events at once (useful for catching up after a pause).
     */
    func drainEvents()  -> [CaptureEvent]

    /**
     * Returns whether F1-F12 are currently excluded from forwarding.
     */
    func excludeFunctionKeys()  -> Bool

    /**
     * Test hook for the Swift harness: deliver a keyboard event through the
     * same target-window posting path used by the event tap. This does not
     * synthesize a source key event; hardware keyboard capture is still owned
     * by the event tap.
     */
    func forwardKeyForTesting(targetWindowId: UInt32?, keycode: UInt16, keyDown: Bool, flags: UInt64) throws

    /**
     * Returns `true` when the tap is currently active.
     */
    func isActive()  -> Bool

    /**
     * Returns the next pending event, or `None` when the queue is empty.
     *
     * Recommended usage: call on a ~16 ms timer in Swift:
     * ```swift
     * while let event = session.pollEvent() { handle(event) }
     * ```
     */
    func pollEvent()  -> CaptureEvent?

    /**
     * When enabled, F1-F12 are not forwarded to the controlled app/window and
     * continue through the original event stream.
     */
    func setExcludeFunctionKeys(exclude: Bool)

    /**
     * Target PID this session controls.
     */
    func targetPid()  -> Int32

}

open class CaptureSession:
    CaptureSessionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_platform_macos_fn_clone_capturesession(self.pointer, $0) }
    }
public convenience init(targetPid: Int32) {
    let pointer =
        try! rustCall() {
    uniffi_platform_macos_fn_constructor_capturesession_new(
        FfiConverterInt32.lower(targetPid),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_platform_macos_fn_free_capturesession(pointer, $0) }
    }




    /**
     * Start capturing. All coordinates must be in CG screen space (top-left
     * origin, y increasing downward — same as CGEventGetLocation and the AX API).
     *
     * Call `poll_event()` on a timer (~16 ms) after this returns to consume events.
     */
open func activate(viewX: Double, viewY: Double, viewW: Double, viewH: Double, targetX: Double, targetY: Double, targetW: Double, targetH: Double, escapeTaps: UInt32, escapeIntervalMs: UInt64)throws  {try rustCallWithError(FfiConverterTypeCaptureError.lift) {
    uniffi_platform_macos_fn_method_capturesession_activate(self.uniffiClonePointer(),
        FfiConverterDouble.lower(viewX),
        FfiConverterDouble.lower(viewY),
        FfiConverterDouble.lower(viewW),
        FfiConverterDouble.lower(viewH),
        FfiConverterDouble.lower(targetX),
        FfiConverterDouble.lower(targetY),
        FfiConverterDouble.lower(targetW),
        FfiConverterDouble.lower(targetH),
        FfiConverterUInt32.lower(escapeTaps),
        FfiConverterUInt64.lower(escapeIntervalMs),$0
    )
}
}

    /**
     * Convenience: activate with `Rect` structs and default escape settings
     * (3 Option-key taps within 1 second).
     */
open func activateWithRects(viewRect: Rect, targetRect: Rect)throws  {try rustCallWithError(FfiConverterTypeCaptureError.lift) {
    uniffi_platform_macos_fn_method_capturesession_activate_with_rects(self.uniffiClonePointer(),
        FfiConverterTypeRect.lower(viewRect),
        FfiConverterTypeRect.lower(targetRect),$0
    )
}
}

    /**
     * Activate with a selected CGWindowID so forwarded mouse events carry
     * window-local hit-test coordinates and background-window routing fields.
     */
open func activateWithWindowId(viewRect: Rect, targetRect: Rect, targetWindowId: UInt32)throws  {try rustCallWithError(FfiConverterTypeCaptureError.lift) {
    uniffi_platform_macos_fn_method_capturesession_activate_with_window_id(self.uniffiClonePointer(),
        FfiConverterTypeRect.lower(viewRect),
        FfiConverterTypeRect.lower(targetRect),
        FfiConverterUInt32.lower(targetWindowId),$0
    )
}
}

    /**
     * Stop capturing and restore the system cursor. Idempotent.
     */
open func deactivate() {try! rustCall() {
    uniffi_platform_macos_fn_method_capturesession_deactivate(self.uniffiClonePointer(),$0
    )
}
}

    /**
     * Drain all pending events at once (useful for catching up after a pause).
     */
open func drainEvents() -> [CaptureEvent] {
    return try!  FfiConverterSequenceTypeCaptureEvent.lift(try! rustCall() {
    uniffi_platform_macos_fn_method_capturesession_drain_events(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Returns whether F1-F12 are currently excluded from forwarding.
     */
open func excludeFunctionKeys() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_platform_macos_fn_method_capturesession_exclude_function_keys(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Test hook for the Swift harness: deliver a keyboard event through the
     * same target-window posting path used by the event tap. This does not
     * synthesize a source key event; hardware keyboard capture is still owned
     * by the event tap.
     */
open func forwardKeyForTesting(targetWindowId: UInt32?, keycode: UInt16, keyDown: Bool, flags: UInt64)throws  {try rustCallWithError(FfiConverterTypeCaptureError.lift) {
    uniffi_platform_macos_fn_method_capturesession_forward_key_for_testing(self.uniffiClonePointer(),
        FfiConverterOptionUInt32.lower(targetWindowId),
        FfiConverterUInt16.lower(keycode),
        FfiConverterBool.lower(keyDown),
        FfiConverterUInt64.lower(flags),$0
    )
}
}

    /**
     * Returns `true` when the tap is currently active.
     */
open func isActive() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_platform_macos_fn_method_capturesession_is_active(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Returns the next pending event, or `None` when the queue is empty.
     *
     * Recommended usage: call on a ~16 ms timer in Swift:
     * ```swift
     * while let event = session.pollEvent() { handle(event) }
     * ```
     */
open func pollEvent() -> CaptureEvent? {
    return try!  FfiConverterOptionTypeCaptureEvent.lift(try! rustCall() {
    uniffi_platform_macos_fn_method_capturesession_poll_event(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * When enabled, F1-F12 are not forwarded to the controlled app/window and
     * continue through the original event stream.
     */
open func setExcludeFunctionKeys(exclude: Bool) {try! rustCall() {
    uniffi_platform_macos_fn_method_capturesession_set_exclude_function_keys(self.uniffiClonePointer(),
        FfiConverterBool.lower(exclude),$0
    )
}
}

    /**
     * Target PID this session controls.
     */
open func targetPid() -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_platform_macos_fn_method_capturesession_target_pid(self.uniffiClonePointer(),$0
    )
})
}


}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCaptureSession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = CaptureSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> CaptureSession {
        return CaptureSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: CaptureSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CaptureSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: CaptureSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> CaptureSession {
    return try FfiConverterTypeCaptureSession.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureSession_lower(_ value: CaptureSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCaptureSession.lower(value)
}


public struct Rect {
    public var x: Double
    public var y: Double
    public var width: Double
    public var height: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Double, y: Double, width: Double, height: Double) {
        self.x = x
        self.y = y
        self.width = width
        self.height = height
    }
}



extension Rect: Equatable, Hashable {
    public static func ==(lhs: Rect, rhs: Rect) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
        hasher.combine(width)
        hasher.combine(height)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRect: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Rect {
        return
            try Rect(
                x: FfiConverterDouble.read(from: &buf),
                y: FfiConverterDouble.read(from: &buf),
                width: FfiConverterDouble.read(from: &buf),
                height: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Rect, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
        FfiConverterDouble.write(value.width, into: &buf)
        FfiConverterDouble.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRect_lift(_ buf: RustBuffer) throws -> Rect {
    return try FfiConverterTypeRect.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRect_lower(_ value: Rect) -> RustBuffer {
    return FfiConverterTypeRect.lower(value)
}


public enum CaptureError {



    case AlreadyActive
    case TapCreationFailed(message: String
    )
    case InternalError
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCaptureError: FfiConverterRustBuffer {
    typealias SwiftType = CaptureError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CaptureError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .AlreadyActive
        case 2: return .TapCreationFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InternalError

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CaptureError, into buf: inout [UInt8]) {
        switch value {





        case .AlreadyActive:
            writeInt(&buf, Int32(1))


        case let .TapCreationFailed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)


        case .InternalError:
            writeInt(&buf, Int32(3))

        }
    }
}


extension CaptureError: Equatable, Hashable {}

extension CaptureError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Events produced by the capture session, polled from Swift via `poll_event`.
 */

public enum CaptureEvent {

    /**
     * Normalised (0–1) cursor position within the host view.
     */
    case mouseMove(normX: Double, normY: Double
    )
    /**
     * The escape sequence (triple Option) was detected; session is now inactive.
     */
    case deactivated
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCaptureEvent: FfiConverterRustBuffer {
    typealias SwiftType = CaptureEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CaptureEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .mouseMove(normX: try FfiConverterDouble.read(from: &buf), normY: try FfiConverterDouble.read(from: &buf)
        )

        case 2: return .deactivated

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CaptureEvent, into buf: inout [UInt8]) {
        switch value {


        case let .mouseMove(normX,normY):
            writeInt(&buf, Int32(1))
            FfiConverterDouble.write(normX, into: &buf)
            FfiConverterDouble.write(normY, into: &buf)


        case .deactivated:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureEvent_lift(_ buf: RustBuffer) throws -> CaptureEvent {
    return try FfiConverterTypeCaptureEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureEvent_lower(_ value: CaptureEvent) -> RustBuffer {
    return FfiConverterTypeCaptureEvent.lower(value)
}



extension CaptureEvent: Equatable, Hashable {}




public enum NtscEffectError {



    case InvalidDimensions(width: UInt32, height: UInt32
    )
    case InvalidBufferLength(width: UInt32, height: UInt32, expected: UInt64, actual: UInt64
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNtscEffectError: FfiConverterRustBuffer {
    typealias SwiftType = NtscEffectError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NtscEffectError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .InvalidDimensions(
            width: try FfiConverterUInt32.read(from: &buf),
            height: try FfiConverterUInt32.read(from: &buf)
            )
        case 2: return .InvalidBufferLength(
            width: try FfiConverterUInt32.read(from: &buf),
            height: try FfiConverterUInt32.read(from: &buf),
            expected: try FfiConverterUInt64.read(from: &buf),
            actual: try FfiConverterUInt64.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NtscEffectError, into buf: inout [UInt8]) {
        switch value {





        case let .InvalidDimensions(width,height):
            writeInt(&buf, Int32(1))
            FfiConverterUInt32.write(width, into: &buf)
            FfiConverterUInt32.write(height, into: &buf)


        case let .InvalidBufferLength(width,height,expected,actual):
            writeInt(&buf, Int32(2))
            FfiConverterUInt32.write(width, into: &buf)
            FfiConverterUInt32.write(height, into: &buf)
            FfiConverterUInt64.write(expected, into: &buf)
            FfiConverterUInt64.write(actual, into: &buf)

        }
    }
}


extension NtscEffectError: Equatable, Hashable {}

extension NtscEffectError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum NtscEffectPreset {

    case low
    case medium
    case hard
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNtscEffectPreset: FfiConverterRustBuffer {
    typealias SwiftType = NtscEffectPreset

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NtscEffectPreset {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .low

        case 2: return .medium

        case 3: return .hard

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NtscEffectPreset, into buf: inout [UInt8]) {
        switch value {


        case .low:
            writeInt(&buf, Int32(1))


        case .medium:
            writeInt(&buf, Int32(2))


        case .hard:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNtscEffectPreset_lift(_ buf: RustBuffer) throws -> NtscEffectPreset {
    return try FfiConverterTypeNtscEffectPreset.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNtscEffectPreset_lower(_ value: NtscEffectPreset) -> RustBuffer {
    return FfiConverterTypeNtscEffectPreset.lower(value)
}



extension NtscEffectPreset: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRect: FfiConverterRustBuffer {
    typealias SwiftType = Rect?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRect.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRect.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCaptureEvent: FfiConverterRustBuffer {
    typealias SwiftType = CaptureEvent?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCaptureEvent.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCaptureEvent.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCaptureEvent: FfiConverterRustBuffer {
    typealias SwiftType = [CaptureEvent]

    public static func write(_ value: [CaptureEvent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCaptureEvent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CaptureEvent] {
        let len: Int32 = try readInt(&buf)
        var seq = [CaptureEvent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCaptureEvent.read(from: &buf))
        }
        return seq
    }
}
public func applyNtscEffectBgrx(width: UInt32, height: UInt32, frameNum: UInt64, preset: NtscEffectPreset, pixels: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeNtscEffectError.lift) {
    uniffi_platform_macos_fn_func_apply_ntsc_effect_bgrx(
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),
        FfiConverterUInt64.lower(frameNum),
        FfiConverterTypeNtscEffectPreset.lower(preset),
        FfiConverterData.lower(pixels),$0
    )
})
}
/**
 * Return the focused window bounds of `pid` in CG screen space (top-left
 * origin, y increasing downward).
 *
 * Tries `AXFocusedWindow` first; falls back to the first element of `AXWindows`.
 * Returns `None` when the process is not accessible or has no windows.
 */
public func getFocusedWindowBounds(pid: Int32) -> Rect? {
    return try!  FfiConverterOptionTypeRect.lift(try! rustCall() {
    uniffi_platform_macos_fn_func_get_focused_window_bounds(
        FfiConverterInt32.lower(pid),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_platform_macos_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_platform_macos_checksum_func_apply_ntsc_effect_bgrx() != 14376) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_func_get_focused_window_bounds() != 56663) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_activate() != 44079) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_activate_with_rects() != 47034) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_activate_with_window_id() != 54436) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_deactivate() != 62063) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_drain_events() != 61282) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_exclude_function_keys() != 44863) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_forward_key_for_testing() != 21093) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_is_active() != 51070) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_poll_event() != 13431) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_set_exclude_function_keys() != 36177) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_method_capturesession_target_pid() != 21875) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_platform_macos_checksum_constructor_capturesession_new() != 29056) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all